### ISSUE TITLE
select flashed away when touch

### ISSUE THREAD

**Issue by lovio** [mcasimir/mobile-angular-ui#111]
``` html
<select name="timeSelector" ng-model="user.start" ng-options="time for time in timeList"></select>
```

``` js
  $scope.timeList = ['10:00', '11:00', '12:00']
```

When I touch the `select` control on my iphone, the selector with appear and flash away. And the nearby form-control will be focused. It confused me for a long time.

Android is ok.

**Comment by ZYongShaun** [comment]
I've had this problem too. i use iphone6 and IOS9, and in wechat browser

**Comment by ZYongShaun** [comment]
@lovio have you solved this problem?

**Comment by lovio** [comment]
@ZYongShaun No longer using `select`
