### ISSUE TITLE
Keyboard hiding input fields

### ISSUE THREAD

**Issue by rjezyk** [mcasimir/mobile-angular-ui#118]
Hello chaps,

I get into this issue while building an app. We got a form with several input fields spread vertically.
If I get to the bottom one and tap on it to fill it out, the soft keyboard is rolling in and covers tapped input entirely, so user can't see what is typing.
I tested it out on your demo part of your site and behaviour is the same.
Issue appears on: mobiles with android 2.3.6, 4.0, 4.4, but also android tablets.

**Comment by ivan-koval** [comment]
@mcasimir any updates here?

**Comment by mcasimir** [comment]
@ivan-koval Hi, you sure it wont work? Also, please report in which device and browser. It has tests running and passing, I also have tested this in my phone and it works, but.. there are versions of 1.2 beta for what that feature was broken.

If you help me to reproduce the issue I will be glad to help you!

**Comment by ivan-koval** [comment]
@mcasimir, I tested it on my Android 4.1.2 device LG Optimus G (in cordova application).
"there are versions of 1.2 beta for what that feature was broken." - do you mean that in current master branch it was broken? But it was working some time earlier (please let me know the commit where it works, I will checkout and test).

**Comment by mcasimir** [comment]
In current in master branch 'was' broken few time ago but now should work. 

The change that made it work again was this:

https://github.com/mcasimir/mobile-angular-ui/blob/master/CHANGELOG.md#v-120-beta3

You can see the diff here: https://github.com/mcasimir/mobile-angular-ui/commit/b3443f5f3b2a8008ca88d09af4e7ad82283bb6d5#diff-21d9f5ff5a838536c317c30e401c1ca4L58

But please try with current release instead: https://github.com/mcasimir/mobile-angular-ui/archive/1.2.0-beta.11.zip

This should work too. Let me know if this is broken again. Thanks!!
