### ISSUE TITLE
Sidebar is not closing when selecting current location

### ISSUE THREAD

**Issue by a-d-c** [mcasimir/mobile-angular-ui#132]
Only applies to V1.2.

You can reproduce within the 1.2 demo.
1. Toggle the left sidebar open.
2. Select any item from the sidebar. Sidebar will close and you'll be navigated to selected location.
3. Re-open left sidebar and click on the highlighted item for your current page. The sidebar will remain open until you click on either a different option, or you click outside the sidebar.

It looks like this is because SharedState.turnOff is only happening in response to $locationChangeSuccess, which isn't happening since you aren't actually changing the location.

**Comment by nirium** [comment]
Has this been fixed? I'm having this issue on beta-11

**Comment by mcasimir** [comment]
See demo code for sidebar, you have to use `ui-turn-off` somewhere around your links, it will close the sidebar on clicks without interfering with them. I think there is no other possible fix, cause is not possible to detect a change in the url that just does not happen.
