### ISSUE TITLE
cannot scrollTo

### ISSUE THREAD

**Issue by xuluan** [mcasimir/mobile-angular-ui#142]
The following code cannot work:

$scope.gotoFooter = function() {
  $("html, body").animate({
    scrollTop: $("#footer").offset().top
  }, 10);
};

But it works when I comment the file: "mobile-angular-ui-base.css"
I think that "mobile-angular-ui-base.css"  disabled  ScrollTo function
How to enable it?
Thanks

**Comment by nirium** [comment]
Im getting "element" is not defined if I use the above code in my controller... Can't get the scrolling to work at all.
