### ISSUE TITLE
Table Pagination

### ISSUE THREAD

**Issue by ghost** [mcasimir/mobile-angular-ui#174]
Evening, I am looking to use the framework in an up and coming project that uses a lot of tabular data - could you point me in the direction of any proved paginated table code - or am I looking at building this from scratch ?

**Comment by frandevel** [comment]
Would be really useful to have at least this type of directives out of the box in the framework. Thanks for pointing this out.
I'm now having issues to integrate ngInfiniteScroll in an angular-mobile-ui based project.
It this planned to be included @mcasimir ?

**Comment by mcasimir** [comment]
It is included yet: http://mobileangularui.com/docs/#-ui-scroll-bottom-ui-scroll-top-

**Comment by frandevel** [comment]
So cool. Thanks a lot @mcasimir

**Comment by mcasimir** [comment]
About pagination directive, could you try to explain, maybe with an example, what kind of directive/component you wish to use.

Maybe something like:

``` html
<div paginate='data as rows by 10' page='currentPage' total-items='totalItems'>
<table>
  <tr ng-repeat='row in rows'></tr>
</table>

<paginationButtons />

</div>
 ```

Then in controller you may set: 

``` js
$scope.currentPage = $routeParams.currentPage || 1;
$scope.data = function(offset, limit) { return $http.get(...) }
$scope.totalItems = $http.get(...); // returns a promise
```

This could be a viable solution, and can be used with something different from tables. Also `totalItems` and `paginate` expressions are recomputed only when `page` changes.

Or even better would be to create a service:

``` js
$scope.paginatedData = paginator({
   getData: fn
   getTotalItems: fn
})
```

``` html
<div paginate='paginatedData by 10'><!-- ... --></div>
```

**Comment by frandevel** [comment]
Hi @mcasimir , this functionality with ui-scroll-bottom should be enought. Right now this is not working for me though.
I have a normal div with the attribute placed and when I scroll to the bottom of the contained table, nothig is fired:
```html
<div id="list-table--div" class="scrollable-content section" ui-scroll-bottom="loadMore()">
        <ng-jobs-table></ng-jobs-table>
    </div>
```
and the directive injects normal stuff:
```html
<table id="jobs-list--table" class="table table-striped" ng-show="result.jobs">
    <tr ng-repeat="job in result.jobs">
        <td>{{job.title}}<br/></td>

        <td>
            <button class="btn btn-primary" value="Details" ng-controller="jobsController" ng-click="showDetails(job.id)">
                <i class="fa fa-info-circle"></i>
            </button>
        </td>
    </tr>
</table>
```
"loadMore()" function is only a window.alert:
```javascript
$scope.loadMore = function () {
        alert("Scrolled!!");
    }
```
My problem is that this function "loadMore()" is not fired.

Thanks for any idea/suggestion/help

Fran
