### ISSUE TITLE
1.2-beta5 Modal Display Issue

### ISSUE THREAD

**Issue by lylepratt** [mcasimir/mobile-angular-ui#182]
Anytime I try to display a modal on 1.2-beta5 I get this warning, and the modal never appears:
`Warning: Attempt to set uninitialized shared state: modalName`

Any ideas what is going on?

Also, when I include a modal in a ng-include template, it errors on mobile:

```
TypeError: Cannot read property 'childNodes' of undefined
```

**Comment by garymazz** [comment]
I just tried this using a browser, I have the same issue. Its not fixed

**Comment by Amerr** [comment]
Please update the docs. and provide a solution for triggering modal window.

**Comment by colliander** [comment]
+1 on getting the "Warning: Attempt to set uninitialized shared state: [modalName]". Any progress?

**Comment by X17** [comment]
@mcasimir @lylepratt 

Facing the same issue:

> Warning: Attempt to set uninitialized shared state: modal2            
> On line Number:   mobile-angular-ui.js:1655       

code snippet
>>    setOne: function(id, value) {
          if (statusesMeta[id] !== undefined) {
            var prev = values[id];
            values[id] = value;
            if (prev !== value) {
              $rootScope.$broadcast('mobile-angular-ui.state.changed.' + id, value, prev);
            }
            return value;
          } else {
            /* global console: false */
            if (console) {
              console.warn('Warning: Attempt to set uninitialized shared state:', id);
            }
          }
        },
