### ISSUE TITLE
1.2-beta.9 Sidebars No Longer Open

### ISSUE THREAD

**Issue by lylepratt** [mcasimir/mobile-angular-ui#185]
Upgraded to 1.2-beta.9 from 1.2-beta-5 and the sidebars no longer open for me. No changes made except for bower install. Anything changed I should be looking for?

I get an uninitialized shared state error:

```
Warning: Attempt to set uninitialized shared state: uiSidebarLeft
```

**Comment by munikumar604** [comment]
Hi lylepratt,
Could you please  help me on this how you solved this issue. I tried with ng-click="dotest()"
$scope.doTest=finction(){
  $rootScope.Ui.toggle('uiSidebarLeft');
}
In debugging , at   $rootScope.Ui.toggle('uiSidebarLeft') opens the sidebar after event It closes automatically
