### ISSUE TITLE
Fastclick error on drag

### ISSUE THREAD

**Issue by samedii** [mcasimir/mobile-angular-ui#187]
Getting this thrown around a lot:
 Uncaught TypeError: Cannot read property '0' of undefined

 For example:
Getting it from dragging on a button (touch event)
In demo; http://mobileangularui.com/demo/#/tabs?uiSidebarLeft, getting it from dragging up and down in sidebar a lot (in chrome emulator mode)

**Comment by RemcovandenBerg** [comment]
Still present now Fastclick is working again:
```
Uncaught TypeError: Cannot read property '0' of undefined
  FastClick.sendClick @ fastclick.js:302
  FastClick.onTouchEnd @ fastclick.js:606
  methods @ fastclick.js:111
  o.set.changeScrollTarget @ overthrow-polyfill.js:101
  o.set.move @ overthrow-polyfill.js:154
```

Looks like an error in the overthrow-polyfill: 
They are creating an endtouch event without a `changedTouches` property. 

Fastclick.js however figures it is always there:
`302:  		touch = event.changedTouches[0];`

https://developer.mozilla.org/en-US/docs/Web/API/TouchEvent/changedTouches
