### ISSUE TITLE
Bottom Navbar scrollable

### ISSUE THREAD

**Issue by apedrolli** [mcasimir/mobile-angular-ui#19]
when you start the project, the bottom navbar is correctly anchored to the bottom of the page. If you resize the browser window, it will correctly change to the mobile format. If you enlarge it again the bottom navbar becomes scrollable, leaving a blank stripe below
![scrollablenavbar](https://cloud.githubusercontent.com/assets/7201878/2628479/2ec13b78-be27-11e3-9c28-462a6031016f.PNG)

**Comment by hbostic** [comment]
What if I want that behavior?  I want the footer to scroll with the rest of the page.  How can I make it so?

**Comment by ciromattia** [comment]
@hbostic like any other element belonging to scrollable-content?

**Comment by hbostic** [comment]
@ciromattia i figured it out, I had to change my css positon from absolute to relative and I had to wrap my ui-view and my footer in scrollable-content.  That gave me want I wanted, thanks

**Comment by deepaksingh0191** [comment]
@hbostic i am trying to make my footer stick to bottom but i dont get it what u meant to say "and I had to wrap my ui-view and my footer in scrollable-content". can you kindly provide me with some sample code.
