### ISSUE TITLE
ng-swipe disables Fastclick on all child elements

### ISSUE THREAD

**Issue by lylepratt** [mcasimir/mobile-angular-ui#191]
Is anyone else having problems with Fastclick on iOS8? All of my clicks are 300ms delayed on my iPhone 5 test device after upgrading to iOS 8 in my MAUI app. I also tried manually attaching Fastclick to the body with no success.

**Comment by mcasimir** [comment]
Hi @lylepratt next release will be all about gestures and `$swipe` service has been redesigned from scratch to use the new `$touch` service. It will be backward compatible.

I will add tests for compatibility with Fastclick too.

Thanks

**Comment by lylepratt** [comment]
@mcasimir This still seems to happen for me. Just updated to beta-11 and any elements inside a container with `ng-swipe-right` or `ng-swipe-left` have slow clicks.

**Comment by ciromattia** [comment]
@lylepratt beta-11 has been released on Dec, 20th, @mcasimir has yet to make a release with the latest fixes. You should try the master branch to check against this issue.

**Comment by lylepratt** [comment]
Ahh, well that explains it. Will try to get my bower to install master.

**Comment by ciromattia** [comment]
in ``bower.json``:
```
"mobile-angular-ui": "git@github.com:mcasimir/mobile-angular-ui.git#master",
```

**Comment by lylepratt** [comment]
yep. Got it, waiting to have an iOS device to test with.

**Comment by lylepratt** [comment]
OK. Fastclick seems to work correctly now that I am using master. However I have opened a separate issue for what seems to be a regression in the swipe behavior:
https://github.com/mcasimir/mobile-angular-ui/issues/205
