### ISSUE TITLE
ui-yield-to stack?

### ISSUE THREAD

**Issue by samedii** [mcasimir/mobile-angular-ui#195]
My problem is that I want to have default navbar buttons but on a single page they are different. After navigating to this page (containing ui-content-for) and going back, the buttons are still replaced.

A solution would be to include my buttons in every page... (ng-include everywhere)

Is there a better one?

I am kind of asking if there is already a better solution / suggesting my idea of solving it (a stack) / hoping to shed light on this design flaw

**Comment by mcasimir** [comment]
Hi, sorry for the delay.

Can you please explain better:

> My problem is that I want to have default navbar buttons but on a single page they are different. After navigating to this page (containing ui-content-for) and going back, the buttons are still replaced.

How is this different from demo? This shouldn't happen, so maybe a bug.

In demo there is a global `ui-yield-to` with defaults

``` html
<div class="btn-group pull-right" ui-yield-to="navbarAction">
  <div ui-toggle="uiSidebarRight" class="btn">
    <i class="fa fa-comment"></i> Chat
  </div>
</div>
```

And then in forms.html it is replaced by this:

``` html
<div ui-content-for="navbarAction">
  <a class='btn' ng-click='login()'>Login</a>
</div>
```

But when you go back/change page the default is restored.

**Comment by samedii** [comment]
Yes, that is exactly what I do. I've used window.history.back() to navigate back or angular ui router $state.go('someState')

Any idea what might be wrong? I'll take a look at it in a couple of days

**Comment by mcasimir** [comment]
Yes you are using UI router that is not supported. Mobile Angular UI respond to `ngRoute` events, using ui router as is you will experience other issues.

If issuing `$stateChangeStart` and `$routeChangeStart` won't conflict with your app
you can use this trick to make ui router work with `mobile-angular-ui`

``` js
myApp.run(function($rootScope){
   $rootScope.$on('$stateChangeStart', function(){
      $rootScope.broadcast('$routeChangeStart');
   });
});
```

**Comment by samedii** [comment]
Thanks!

**Comment by JonnyVy** [comment]
This works:

myApp.run(function($rootScope){
   $rootScope.$on('$stateChangeSuccess', function(){
      $rootScope.$broadcast('$routeChangeSuccess');
   });
});
