### ISSUE TITLE
Modals not working, at all.

### ISSUE THREAD

**Issue by nirium** [mcasimir/mobile-angular-ui#196]
Hi. I've updated to the latest version and modals wont show up, at all. Other threads here never tell the solution of any related questions.

In my index file I have this:

``` html
<div ui-yield-to="modals"></div>

And then on another page:

<div ui-content-for="modals">
	<div class="modal modal-overlay" ui-if="accountOverlay" ui-state="accountOverlay">
		<h2>Bla bla</h2>
		<span><b>Bla bla</b></span>
		<button class="button fill-width" ui-turn-off="accountOverlay">Stäng</button>
	</div>
</div>
```

and this modal will NOT show up by using this:

``` js
SharedState.initialize($scope, 'accountOverlay');
$scope.showAccountOverlay = function() {
	SharedState.toggle('accountOverlay', 'on');
}
```

it doesn't work by assigning ui-toggle on an element either...

How is this supposed to work??

**Comment by nirium** [comment]
Don't know what happened with the post above but the Bla bla part should be this:

**Comment by mcasimir** [comment]
Try this:

``` js
SharedState.turnOn('accountOverlay');
```

**Comment by nirium** [comment]
SharedState.initialize($scope, 'accountOverlay');
			$scope.showAccountOverlay = function() {
				SharedState.turnOn('accountOverlay');
			}

Still no luck :(

**Comment by mcasimir** [comment]
Some hint to debug:

```
<div ui-yield-to="modals"></div>

And then on another page:

<div>accountOverlay: {{ Ui.active('accountOverlay') ? 'active' : 'inactive' }}</div>

<div ui-content-for="modals">
    <div class="modal modal-overlay" ui-if="accountOverlay" ui-state="accountOverlay">
        <h2>Bla bla</h2>
        <span><b>Bla bla</b></span>
        <button class="button fill-width" ui-turn-off="accountOverlay">Stäng</button>
    </div>
</div>
```

``` js
        SharedState.initialize($scope, 'accountOverlay');
        $scope.showAccountOverlay = function() {
            console.log('here');
            SharedState.turnOn('accountOverlay');
            console.log(SharedState.values());
        }
```

**Comment by nirium** [comment]
I'm getting "accountOverlay: inactive". So what's wrong here? :D

**Comment by mcasimir** [comment]
What about console output?

**Comment by nirium** [comment]
My bad, when clicking the image that's supposed to open the overlay it says "accountOverlay: active". No console output

**Comment by mcasimir** [comment]
No console output means this has not been called?

``` js
$scope.showAccountOverlay = function() {
    console.log('here');
    SharedState.turnOn('accountOverlay');
    console.log(SharedState.values());
}
```

**Comment by nirium** [comment]
I'm getting "here" and then an object with this:

accountOverlay
	
	true
	
mainSidebar
	
	false
	
rightSidebar
	
	true

**Comment by mcasimir** [comment]
Ok then try to remove `ui-content-for="modals"` or inspect dom and try to see if modal is attached but just not displaying.

**Comment by nirium** [comment]
The HTML inside the <div ui-yield-to="modals"> can be seen as the account overlay but it's grayed out:

	<div class="modal modal-overlay ng-scope" ui-if="accountOverlay" ui-state="accountOverlay">
		<h2>Information</h2>
		<span><b>Tillgängligt</b></span>
		<p>Tillgängligt är det belopp som inte är reserverat i någon utmaning. 
		Detta belopp kan utbetalas, eller användas för att skapa/acceptera utmaningar om riktiga pengar från vänner.</p><br>
		<span><b>Reserverat</b></span>
		<p>Reserverat belopp är det belopp som är låst i pågående utmaningar. 
		När en vinnare/förlorare är utsedd så släpps det reserverade beloppet till potten.</p><br>
		<span><b>Totalt</b></span>
		<p>Ditt saldo är det totala beloppet du har tillgänglighet till, samt beloppet du har reserverat i pågående utmaningar.</p><br>
		<button class="button-gumbler fill-width" ui-turn-off="accountOverlay">Stäng</button>
	</div>


And by removing the content-for it's not even there (not even grayed out)

**Comment by mcasimir** [comment]
removing `content-for` you will see it in another place.
It is visually grayed out but like that is actually attached. Just try to turn off the modal, you should not see the code but just the comment .

**Comment by mcasimir** [comment]
Sorry to not have noticed first: your HTML is incomplete:

``` html
<div ui-content-for="modals">
  <div class="modal" ui-if="modal1" ui-state='modal1'>
    <div class="modal-backdrop in"></div>
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button class="close" 
                  ui-turn-off="modal1">&times;</button>
          <h4 class="modal-title">Modal title</h4>
        </div>
        <div class="modal-body">
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Distinctio quo illum nihil voluptatem earum optio repellendus, molestias illo facere, ea non. Possimus assumenda illo accusamus voluptatibus, vel corporis maxime quam.</p>
        </div>
        <div class="modal-footer">
          <button ui-turn-off="modal1" class="btn btn-default">Close</button>
          <button ui-turn-off="modal1" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>
</div>
```

**Comment by nirium** [comment]
Even if I try with your modal example and rename the modal to "accountOverlay" the content in the DOM is still grayed out and no modal shows...

**Comment by mcasimir** [comment]
Sorry, again grayed but present is good, it means it is attached to dom so the SharedState stuff is working. The fact that you see that code with `content-for` means content-for works, so the latter problem is showing it.

Have you updated css also? Get rid of any ui-state ui-if, modal should display, if not your css maybe out of sync.

**Comment by nirium** [comment]
I'm seeing them now! Seems that indeed the css was out of sync. However even when the modal is closed I can see it in the background. Is there any fix for that? If you know what I mean.

Really appreciate the support.

**Comment by mcasimir** [comment]
Thanks to you, any feedback is gold.

> Modals are basically the same of Bootstrap 3 but you have to use uiState with ngIf/uiIf or ngHide/uiHide to activate/dismiss it. By default both modals and overlay are made always showing up by css rule .modal {display:block}, so you can use it with ngAnimate and other angular directives in a simpler way.

So now you that you have the right css, if I understood good, try to put back `ui-if` and it should work as expected.

**Comment by nirium** [comment]
I do have the ui-if etc.. But on the main page I'm having a slightly added opacity and the overlay can be seen in the background even when not called upon

**Comment by mcasimir** [comment]
Maybe you have `<div class="modal-backdrop in"></div>` with overlay? It is not necessary. Anyway double-check your html to make it like the overlay example in docs. It should work.

**Comment by nirium** [comment]
Will check that out. Also it seems that the overlays doesn't cover the sidebar like it did before

**Comment by mcasimir** [comment]
Thats due to where you place the `yield-to`. Anyway it will work if you follow the docs or the new demo layout and examples.

I'm closing, but feel free to reopen or just ask more clarifications here. It is important to understand what is clear and what not to document it properly.

Thanks

**Comment by nirium** [comment]
Just want to give a heads up to people that when migrating, make sure that the css is brought along. That was a huge miss on my end.

**Comment by nirium** [comment]
Seems that I've got everything set up npw except one last thing... I have multiple modals on several places scattered around the application. The yield-to only seems to register one of the modals and the other simply get's an error when trying to call them (e is undefined). Sometimes modal A works but not B and sometimes B works but not modal A.

**Comment by mcasimir** [comment]
`content-for` do not append it replaces. If you need more modals to be in the same `yield-to` put all of them in the same `content-for` section. If you need more modals from different views just use more `yield-to` sections. Ie.

``` html
<div ui-yield-to="modals"></div>
<div ui-yield-to="accounts-modals"></div>
<div ui-yield-to="sales-modals"></div>
```

**Comment by nirium** [comment]
Thanks. Felt pretty stupid that I didn't test this out. All my questions are now answered and thanks for the support!
