### ISSUE TITLE
ng-swipe-right && ng-swipe-left assigned to function called twice

### ISSUE THREAD

**Issue by nirium** [mcasimir/mobile-angular-ui#197]
Hello,

I've assigned ng-swipe-left & ng-swipe-right to my body element. This calls a function which will handle the states of the sidebars, however the function gets called twice which kinda messes with what I want to do.

Any ideas?

**Comment by nirium** [comment]
No idea? I'm struggling with this. Using ng-swipe on both main page and sidebars give unpredicted results. I want to call a function on ng-swipe-right:

if(rightbar is open) close it
else open leftbar

but since it get's called twice it will always scroll from sidebar A to sidebar B if one is open, eliminating the purpouse of my desired result.

**Comment by mcasimir** [comment]
Sorry, do you mean `ng-swipe` from `mobile-angular-ui.gestures` module or the one from `ngTouch`?

**Comment by nirium** [comment]
It seems that I am using ngTouch. So the problem might be that, that one and the one from your library gets called? I think I might be using both which may the issue here. Anyway, if I remove ngTouch entirely will ng-click still work through angular mobile?

Thanks for your reply

**Comment by nirium** [comment]
My mistake entirely. Didn't pay attention to the docs. I now removed ngTouch from the whole application and it now works as expected.

**Comment by mcasimir** [comment]
@nirium I will make this more evident in docs. The next release i planned to publish today has a lot of fixes and features for touch devices, and a **brand new documentation**, i suggest you to update immediately.

Your question are always appreciated!
