### ISSUE TITLE
Swipes Rarely Register since latest Swipe update

### ISSUE THREAD

**Issue by lylepratt** [mcasimir/mobile-angular-ui#205]
The previous ng-swipe implementation worked great on Android and iOS. However, since you've refactored it, I've updated to master and now swipes rarely register on my Android Nexus 5 or my iPhone 4S. I get maybe 1 recognition out of 10.

Not really sure why this is, but wanted to bring it to your attention. If there is something specific I can test for you to provide more information, let me know.

**Comment by mcasimir** [comment]
Hi @lylepratt,
From what you said, i think everything is working fine, but thresholds I set are too strict.

Try to hack `swipe.js` code, should be in your `bower_components/mobile-angular-ui/src/js/gestures/swipe.js`. You will see some constants.

It may be the required speed is too fast, or the angle too narrow.

If you manage to find proper values, please report them here!

Thank you!

**Comment by lylepratt** [comment]
@mcasimir will do. I'm also having an issue where scroll areas will not scroll. Could this be related to that?

**Comment by mcasimir** [comment]
No it's more likely related to the new nobounce feature, and prevention of touchmove defaults. Are your scroll areas not using `scrollable-content`?

**Comment by lylepratt** [comment]
They are using the `scrollable-content` class.

Screenshot:
https://www.dropbox.com/s/fbtdtsdkuvx8ien/Screenshot%202015-01-20%2013.47.45.png?dl=0

I can open a different issue for this so this one is not clogged.

**Comment by mcasimir** [comment]
Probably the same hack fixing bounce on IOs break scroll on Android.

**Comment by mcasimir** [comment]
Don't know it seems to work for me.. could you try with the demo too?

**Comment by mcasimir** [comment]
Any update about these two?

**Comment by mcasimir** [comment]
If you help me a little I can release today.

**Comment by lylepratt** [comment]
Hi Sorry. I will do some testing asap.

**Comment by lylepratt** [comment]
Demo web app seems to work correctly. Am going to spend some time with our app to see if I can get more information. Definitely something changed recently though that is preventing it from working on our end.

**Comment by mcasimir** [comment]
I'll attach here the code involved in preventing overscroll:

Nobounce.js
``` js
/**
 * Enable prevention of window bounce in IOS.
 *
 * Requiring this module the `touchmove.preventDefault` logic is inverted. 
 * So any `touchmove` default behaviour is automatically prevented.
 * 
 * If you wish to allow the default behaviour, for example to allow 
 * inner elements to scroll, you have to explicitly setup `e.allowTouchmoveDefault` 
 * to `true`.
 *
 * Mobile Angular UI already handles this for `scrollable` elements.
 *
 * You can easily disable this for an element, or under some circumstances through
 * the `allowTouchmoveDefault` service provided in this module.
 * 
 * @module mobile-angular-ui.core.nobounce
 */
(function () {
  'use strict';
  var module = angular.module('mobile-angular-ui.core.nobounce', []);

  if ('ontouchmove' in document) {
    module.run(function() {
      angular.element(document).on('touchmove', function(e) {
          console.log('!preventing');
        if (e.allowTouchmoveDefault !== true) {
          console.log('preventing');
          e.preventDefault();
        }
      });
    });
  }

  /**
   * Bind a listener to an element to allow `touchmove` default behaviour
   * when `touchmove` happens inside the bound element.
   * 
   * You can also provide a function to decide when to allow and 
   * when to prevent it.
   *
   * ``` js
   * // always allow touchmove default
   * allowTouchmoveDefault(myelem);
   * 
   * // allow touchmove default only under certain conditions
   * allowTouchmoveDefault(myelem, function(touchmove){
   *   return touchmove.pageY > 100;
   * });
   * ```
   *
   * @param {Element|$element} element The element to bind.
   * @param {function} condition A `function(touchmove)⟶boolean` to decide
   *                             whether to allow default behavior or not. 
   * 
   * @service allowTouchmoveDefault
   * @as function
   * @returns function Function to unbind the listener
   */
  
  module.factory('allowTouchmoveDefault', function(){
    var fnTrue = function() { return true; };

    if ('ontouchmove' in document) {
        return function($element, condition) {
          condition = condition || fnTrue;

          var allowTouchmoveDefaultCallback = function(e) {
            if (condition(e)) { e.allowTouchmoveDefault = true; }
          };

          $element = angular.element($element);
          $element.on('touchmove',  allowTouchmoveDefaultCallback);

          $element.on('$destroy', function() {
            $element.off('touchmove', allowTouchmoveDefaultCallback);
            $element = null;
          });

          return function() {
            if ($element) {
              $element.off('touchmove', allowTouchmoveDefaultCallback);              
            }
          };
        };
    } else {
      return angular.noop;
    }
  });

}());
```

Scrollable.js
``` js
        // Handle nobounce behaviour
        if ('ontouchmove' in document) {
          var allowUp, allowDown, prevTop, prevBot, lastY;
          var setupTouchstart = function(event) {
            allowUp = (scrollableContent.scrollTop > 0);
            allowDown = (scrollableContent.scrollTop < scrollableContent.scrollHeight - scrollableContent.clientHeight);
            prevTop = null; 
            prevBot = null;
            lastY = event.pageY;
          }

          $element.on('touchstart', setupTouchstart);
          $element.on('$destroy', function() {
            $element.off('touchstart');
          });

          allowTouchmoveDefault($element, function(event) {
            var up = (event.pageY > lastY), down = !up;
            lastY = event.pageY;
            console.log(up, allowUp, down, allowDown);
            return (up && allowUp) || (down && allowDown);
          });
        }
```

**Comment by lylepratt** [comment]
Does not do me much good unfortunately. Our app we are having problems with installs MAUI via bower and its very difficult for me to alter our build processes to load customized libraries. So far no progress.

**Comment by lylepratt** [comment]
Is there an easy way to globally disable this in a MAUI project? Seems like binding these touchmove listeners to elements should require the developer's action. The vast majority of people will want default (bounce) behavior and the overhead for this is not needed.

**Comment by lylepratt** [comment]
I commented out the `nobounce` code, and scrolling works in our app again.

**Comment by lylepratt** [comment]
I adjusted some of the default for the `swipe` service and its working much better for me now:

```
var VELOCITY_THRESHOLD = 500; // px/sec  OLD=1000
var MOVEMENT_THRESHOLD = 10; // px
var TURNAROUND_MAX = 10; // px
var ANGLE_THRESHOLD = 10; // deg  OLD=4
```

**Comment by mcasimir** [comment]
Let's try this then

allowTouchmoveDefault(document.body)

I may make this optional, but its likely one would disable browser defaults to reproduce custom behaviour so this could be a starting point to support more complex components like drag up to open a bottom menu.

**Comment by lylepratt** [comment]
The bigger question is: Why is it breaking things in the first place?

**Comment by lylepratt** [comment]
Placing `allowTouchmoveDefault(document.body);` in `app.run` does not seem to help.

**Comment by lylepratt** [comment]
Also: when I said the "demo" worked, I was testing on the Demo on your website. It appears that that is not the latest version though. So, after getting gulp working on my comp and trying out the latest Demo included in the master branch, I can confirm that scrolling DOES NOT work on my Android 5.0.1 Nexus 5 phone.

**Comment by mcasimir** [comment]
Ok for now I think I will keep the hack only for IOS. Although I really wish it to be consistent for android devices too someday.

**Comment by lylepratt** [comment]
I'll try to do some additional work on this this weekend.

**Comment by mcasimir** [comment]
Tested with android device and fixed.. I hope!

**Comment by lylepratt** [comment]
Updated to master and it seems to work on Android now.

**Comment by mcasimir** [comment]
Fine! I moved nobounce to a directive `preventTouchmoveDefaults`  so it is optional now as you suggested.
