### ISSUE TITLE
Error in initial setup

### ISSUE THREAD

**Issue by migo** [mcasimir/mobile-angular-ui#209]
Hi,

I've just tried to follow the initial setup instructions.
I ran

    yo mobileangularui

(finished without errors)
and then

    gulp build

which finished with an error:

```
[14:05:39] Finished 'images' after 24 ms

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: 'font-awesome/less/spinning.less' wasn't found in file /Users/mg/projects/lytr/bower_components/mobile-angular-ui/src/less/mobile-angular-ui.less line no. 1
```

It seems that "spinning.less" is no longer included in font-awesome?

Cheers,
Michael

**Comment by mcasimir** [comment]
Hi it happens `font-awesome` changed something these days. For now, just open your `bower.json` and hardcode a previous release, 4.2 should work.

I'm fixing it in sources too.

**Comment by jcwatson11** [comment]
Thanks. This helped me.

**Comment by EeKay** [comment]
Thanks for the tip guys!
