### ISSUE TITLE
include ng-touch may cause pointer-events: none?

### ISSUE THREAD

**Issue by lovio** [mcasimir/mobile-angular-ui#215]
I included `ng-touch` to enable `ng-swipe-*`, but my webapp will sometimes unable to be tapped.
I've no idea whether `mobile-angular-ui` is conflict with `ng-touch`.
Will it set `pointer-events: none` to the input element?

**Comment by mcasimir** [comment]
`ng-touch` is not compatible with mobile-angular-ui!

You may think to update to current master and use `mobile-angular-ui.gestures` instead.

**Comment by RemcovandenBerg** [comment]
closed due to age.
