### ISSUE TITLE
Pass value to modal

### ISSUE THREAD

**Issue by persianturtle** [mcasimir/mobile-angular-ui#218]
What would be the best way to pass a value to a modal?

**Comment by juriw** [comment]
With RouteParams?

**Comment by persianturtle** [comment]
What I ended up doing was creating an intermediate function on the button that shows the modal which sets the values from inside an ng-repeat to properties on the $scope that can be used in the function called by the modal button.

**Comment by RemcovandenBerg** [comment]
Seems like you are using the same solution I would use. ;-)
