### ISSUE TITLE
How to not make sidebar close with links?

### ISSUE THREAD

**Issue by eaflores4** [mcasimir/mobile-angular-ui#219]
Nice directive you have here! I have removed the ui-turn-off='uiSidebarLeft' but the sidebar still closes when a link is clicked inside the sidebar. Is there a way to remove this effect? Thank You.

**Comment by RemcovandenBerg** [comment]
Yes, you can use ui-state="uiSideBarLeft" instead as you probably did and remove the  ui-track-as-search-param='true' attribute. 

But if you use links (href) to navigate, it will still close on navigation. 
This is the default behaviour for now, and is not easily changed.
