### ISSUE TITLE
404 css's

### ISSUE THREAD

**Issue by GiankOtarola** [mcasimir/mobile-angular-ui#225]
In index appear css/app.min.css and css/responsive.min.css, but those files are not in the folder of the app. The files that i can find are, mobile-angular-ui-base.min.css, mobile-angular-ui-desktop.min.css,mobile-angular-ui-hover.min.css, mobile-angular-ui-migrate.min.css.
I have to replace for one of the folder that i find?

regards!

**Comment by RemcovandenBerg** [comment]
You have to tell us which project, you are referring to. In the current demo there are no references to the .css files you named.
