### ISSUE TITLE
Question about controlling REST data in sidebar (user specific data)

### ISSUE THREAD

**Issue by juriw** [mcasimir/mobile-angular-ui#227]
Hello out there :)

I'm kinda new to angularjs and I'm making a single page application (SPA) where I need to have some menu items in the sidebar that needs to be updated with a REST service.

The menu items is links to open orders in a support system, so after the user has logged into the system all that specific users support cases should be displayed in the sidebar.

The REST services is fully functional and the get calls works as they should, but how is the smartest way of implementing a controller for the sidebar? 
I'm using the mobile-angular-ui framework so that the sidebar is located in the index.html file and thereby controlled by the "app" controller. So when my users are browsing at the login screen (index.html) then all the get calls fails because they are called before user credentials are being validated.

Kind regards,
JW

**Comment by scrx** [comment]
Sorry but that's is not relevant issue for mobile-angular-ui you should ask this kind of question on stackoverflow.com or take a look at angularjs docs.

**Comment by RemcovandenBerg** [comment]
Closed, out of scope.
