### ISSUE TITLE
Not support fastClick in this version?

### ISSUE THREAD

**Issue by tinhdx** [mcasimir/mobile-angular-ui#230]
In last version "mobile-angular-ui-master" have supported fastClick. So in mobile, when tap a link or button is smooth. But in this version not support. I hope Team will support it
Thank you.

**Comment by RemcovandenBerg** [comment]
It is actually supported, but you have to add it to your project as a dependency:

http://mobileangularui.com/docs/#fastclick

**Comment by mcasimir** [comment]
@RemcovandenBerg I think this is a bug. Fastclick is compiled along with sources. @tinhdx what do u mean with:

> In last version "mobile-angular-ui-master" have supported fastClick

Is the current master not working?

**Comment by RemcovandenBerg** [comment]
Ok I see.. 'last' not meaning version 1.1.. My bad.

**Comment by RemcovandenBerg** [comment]
Tested (on mobile) and confirmed it as a fix.
