### ISSUE TITLE
Value return from modal

### ISSUE THREAD

**Issue by HelloCui** [mcasimir/mobile-angular-ui#232]
How I can get the value return from modal?

**Comment by ciromattia** [comment]
There's no such "return value", you can get some IPC by managing $scope (or $rootScope) variables.

**Comment by HelloCui** [comment]
@ciromattia I am new to angularjs, can you give me a sample?
Thank you!

**Comment by kevindstanley1988** [comment]
This is not an 'issue' it is a question, but you can assign $rootScope values inside of a modal controller scope by dependency injecting $rootScope to that controller. If you include angular-ui's $modal service you can code inside a controller or service and dependency inject $modal and use it like below to access the returned value of the promise.

app.controller('modalControllerId',['$rootScope','$modal',function($rootScope,$modal){
var modalSettings ={//options here}
$modal.open(modalSettings).then(function(result){ $rootScope.storeReturnValue = result; });
}

**Comment by RemcovandenBerg** [comment]
Seems answered.
