### ISSUE TITLE
Back button and sidemenu

### ISSUE THREAD

**Issue by napcat** [mcasimir/mobile-angular-ui#233]
I'm facing some problems with back button on Android (and in other platforms).

When the back button is pressed, if the side bar is open or has been open, nothing will happen. The Query string injected to the state, when the side menu is open, affects the navigation. 
Can the side menu "state" be ignored? I noticed in the examples reloadOnSearch is set to false, but I'm using ui-router and not ng-router, and that seems to break the thing.

Also, in iOS, since there isn't any hard back button I'm trying to create a soft back button, but how can I manage the navigation? 

I think $window.history.go(-1); will do the trick, but since there's a problem with the side menu state I want to skip it. How can I check the state name of $window.history.go(-1); before calling the method?

Thank you.

**Comment by RemcovandenBerg** [comment]
Take a look at Issue #173 for more information on how to get support for ui-router. Let me know if this solves your problem.

**Comment by RemcovandenBerg** [comment]
Closed due to not responding.
