### ISSUE TITLE
Whenever I try to open new link it download that html file which I want to open

### ISSUE THREAD

**Issue by poojacmore** [mcasimir/mobile-angular-ui#236]
Hello,
I have problem with mobile angular ui.
I have used just an anchor tag and trying to open another page when I click on the particular link.
In this case, that links' html file is getting downloaded instead of opening the link in my localhost.
What can be the cause of it?
Please reply

Regards,
Pooja

**Comment by akki12345** [comment]
It would be nice for a way to disable the default click action from ng-click (or some mechanism other than using "javascript:" in the href to short-circuit it)

**Comment by RemcovandenBerg** [comment]
Please provide a simple example with your html. It seems like you are using something wrong. Let me have a look to guide you in the right direction.

**Comment by poojacmore** [comment]
Hello RemcovandenBerg,
My problem is solved!!
I was doing it in wrong way, actually I am using angular-js with Structr, and didn't know earlier about about setting file type to html. Once I set that, everything worked perfectly.

Thanks for your help.

Regards,
Pooja
