### ISSUE TITLE
Created some new pages but not able to add them in demo.js

### ISSUE THREAD

**Issue by poojacmore** [mcasimir/mobile-angular-ui#238]
Hello All,
I have created some new pages, but I am not able to open these pages on click event of any button. These newly created pages are getting downloaded when I try to open them with window.open function.
Can someone help me, how I can add these pages to demo.js?

Any hint will be a great help.

Regards,
Pooja

**Comment by RemcovandenBerg** [comment]
You have to define routes with the $routeprovider from AngularJs. See http://viralpatel.net/blogs/angularjs-routing-and-views-tutorial-with-example/
for a nice tutorial and some examples.
