### ISSUE TITLE
Scroll in demo not works in 36.0.1  (ubuntu, desktop) 

### ISSUE THREAD

**Issue by mikethejet** [mcasimir/mobile-angular-ui#240]
Scroll in demo not works in 36.0.1  (ubuntu, desktop) 
When i click on item i go to homepage.

**Comment by RemcovandenBerg** [comment]
Maybe I am misunderstanding your question, but what is your expectation?

Each item in the scroll page is a link to the homepage. The scroll-demo is showing you the UI and scrollable feature of a long list of items.
