### ISSUE TITLE
autocomplete not available

### ISSUE THREAD

**Issue by poojacmore** [mcasimir/mobile-angular-ui#242]
Is there is any possible way to implement autocomplete with mobile angular ui? Like jQuery

**Comment by RemcovandenBerg** [comment]
Mobile-angular-ui does not provide such component/directive at the moment.
AngularJS is extensible by nature, so you could drop in a specialized directive created for those purposes. 
Have look at https://github.com/JustGoscha/allmighty-autocomplete

**Comment by poojacmore** [comment]
Thank you so much for this hint.
I will surely implement in this way.

You solved my problem.

Regards,
Pooja

**Comment by poojacmore** [comment]
Hi RemcovandenBerg,
I want to use autocomplete functionality with the entity fetched from the database.
This is something I am trying to implement. I am using REST API,

$scope.autcomplete = function(typedthings) {  
    var scrollItems1 = [];
    var newItems =[];
   
   $http.get('/structr/rest/study/default').success(function(data, status, headers, config) {
      scrollItems1 = data.result.map(function(study1) {
       return study1.Domain;
     });
     console.log(scrollItems1);
     $scope.scoll = scrollItems1;
     newItems = scrollItems1(typedthings);
     newItems.then(function(data){
       $scope.scoll = data;
     });
  }).
  error(function(data, status, headers, config) {
    console.log(data, status, headers, config);
 });
  };

I am calling this on on-type event
Its throwing lots of errors.
Can you please check where I am making mistake..
It will be a great help.

Regards,
Pooja

**Comment by RemcovandenBerg** [comment]
It should be as simple as: 


    <autocomplete ng-model="yourchoice" data="autoCompleteChoices" on-type="autcomplete"></autocomplete>


    
    $scope.autoCompleteChoices = [];
    
    $scope.autcomplete = function(typedthings) {
    
    	$http.get('/structr/rest/study/default')
    	.success(function(data, status, headers, config){
    
    		    $scope.autoCompleteChoices = data.result.map(function(study1) {
    		 	  return study1.Domain;
    		    });
    		
    	})
    	.error(function(data, status, headers, config) {
    		console.log(data, status, headers, config);
    	});
    };

But I have not tested nor am I an expert or did I ever use this component. If you have further questions about it's usage, I think it is best to ask them on at the autocomplete project itself on Github.

**Comment by poojacmore** [comment]
Hey thanks a lot.. I made it very complicated actually..
Your code worked, but just a small problem now.. I hope you  can help me, and sorry as I am giving you trouble.
It is shifting the screen down when the list is loaded on page,
![autocomplete](https://cloud.githubusercontent.com/assets/11183873/7054629/0a7cc8d0-de3e-11e4-931f-f1a5bd47f295.png)
Can you help with this please?

Regards,
Pooja

**Comment by RemcovandenBerg** [comment]
Check your z-index, in the css of this component. It is set to 1 which should exclude it from the main. Maybe you forgot to add autocomplete.css

**Comment by poojacmore** [comment]
Hi Remco,
I have added autocomplete.css at correct path still getting that behavior.

Regards,
Pooja

**Comment by RemcovandenBerg** [comment]
Did you try increasing it's value? 
You can do this in your own css file by overriding the css style like this:

    body .autocomplete ul{
        z-index: 3000;
    }

**Comment by poojacmore** [comment]
Hi Remco,
I changed the z-index in autocomplete.css where it was 1 before to 3000 and
added 3000 in demo.css as well.
Still getting the same result.

Do you have any idea what can be the cause?

Regards,
Pooja

**Comment by RemcovandenBerg** [comment]
Try reading up on the subject of css layers / z-index  and positioning.
http://www.echoecho.com/csslayers.htm

**Comment by poojacmore** [comment]
Hey Remco,
Thanks a lot :) for your hints.. :)
It worked..

Thank you so much


Regards,
Pooja
