### ISSUE TITLE
Is it possible to fetch data from another web-page?

### ISSUE THREAD

**Issue by poojacmore** [mcasimir/mobile-angular-ui#244]
Hello All,
I am developing on mobile application where I need to fetch some details from another web page.
Is there is any way to do that in mobile angular ui?
Each time I get this error,
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8082' is therefore not allowed access.

Can anyone give me any hint?

It will be a great help.

Thanks in advance.

Regards,
Pooja

**Comment by konradluka** [comment]
Hi,
It is CORS problem, you must set headers on server you try to get data, example and doc in nodejs bellow:
https://nodejs.org/api/http.html#http_response_setheader_name_value
// Add headers
app.use(function (req, res, next) {

    // Website you wish to allow to connect
    res.setHeader('Access-Control-Allow-Origin', 'http://localhost:8082');

    // Request methods you wish to allow
    res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS, PUT, PATCH, DELETE');

    // Request headers you wish to allow
    res.setHeader('Access-Control-Allow-Headers', 'X-Requested-With,content-type');

    // Set to true if you need the website to include cookies in the requests sent
    // to the API (e.g. in case you use sessions)
    res.setHeader('Access-Control-Allow-Credentials', true);

    // Pass to next layer of middleware
    next();
});

Best,
Konrad

**Comment by poojacmore** [comment]
Hi Konrad,
Thanks a lot for your hint. But I not getting how to set these headers.
I am getting so many errors after trying this.
I am trying to fetch data from "
http://www.ncbi.nlm.nih.gov/pubmed/23456789?report=medline&format=text"
this location.
Can you please tell me, where I should initialize the app.use function?

It will be a great help.

Thanks and Regards,
Pooja

**Comment by RemcovandenBerg** [comment]
Pooja, 
This is a server side issue. Nothing we can do for you here, so closing this issue.
Good luck with it.
