### ISSUE TITLE
Demo from mobileangularui.com show error

### ISSUE THREAD

**Issue by lynn-atech** [mcasimir/mobile-angular-ui#260]
I've downloaded the demo from official website.When run index.html(in demo folder) in chrome,the console threw errors:
1:file:///E:/dist/css/mobile-angular-ui-hover.min.css net::ERR_FILE_NOT_FOUND 2:file:///E:/dist/css/mobile-angular-ui-base.min.css net::ERR_FILE_NOT_FOUND
3:file:///E:/dist/css/mobile-angular-ui-desktop.min.css net::ERR_FILE_NOT_FOUND
4:file:///E:/demo/demo.css net::ERR_FILE_NOT_FOUND
5:file:///E:/dist/js/mobile-angular-ui.min.js net::ERR_FILE_NOT_FOUND
6:file:///E:/dist/js/mobile-angular-ui.gestures.min.js net::ERR_FILE_NOT_FOUND
7:file:///E:/demo/demo.js net::ERR_FILE_NOT_FOUND
8: file://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.0/angular.min.js net::ERR_FILE_NOT_FOUND
9: file://cdnjs.cloudflare.com/ajax/libs/angular.js/1.3.0/angular-route.min.j net::ERR_FILE_NOT_FOUND
10: file://www.google-analytics.com/analytics.js net::ERR_FILE_NOT_FOUND

**Comment by flashdave1973** [comment]
are you running it on your desktop? Or on your localhost?

Your page references are document relative, not root relative. I would assume you are trying to open and view outside your local web server root. see <a target="_blank" href="http://www.maketecheasier.com/setup-local-web-server-all-platforms/">How to Set Up a Local Web Server...</a> for more information on setting up a local web server.

**Comment by estvmachine** [comment]
The safe way is ussing a server, the more simple i know and if you are ussing node use ""http-server"", try just download the mobile-angular.ui and then:

1. npm install -g http-server
2. http-server 
3. Reach to the tree folders to bower_components/mobile-angular-ui/demo

**Comment by mcasimir** [comment]
@lynn-atech Yep you need to run it through a server.

@estvmachine Thank U!

**Comment by estvmachine** [comment]
Oh i dont know that!, thanks!
