### ISSUE TITLE
Error in Accordion Documentation

### ISSUE THREAD

**Issue by mdangschat** [mcasimir/mobile-angular-ui#265]
http://mobileangularui.com/docs/#accordion

`<div ui-if="myAccordion == i">` should be `<div ui-if="myAccordion == i" ui-scope-context="i">`

**Comment by laranicolas** [comment]
+1 @mdangschat

**Comment by alex-signature-it** [comment]
Wow, thanks! That attribute is essential for using accordion with ng-repeat.

**Comment by caiotomazelli** [comment]
Thanks, I also needed this!

**Comment by mcasimir** [comment]
Thanks guys, does it affect latest docs too? http://mobileangularui.com/docs/accordion/
