### ISSUE TITLE
infinite-scroll/pull-to-refresh

### ISSUE THREAD

**Issue by fuzhentao** [mcasimir/mobile-angular-ui#267]
hey guys
has anybody use infinite-scroll or pull-to-refresh plugin with mobile-angular-ui?

**Comment by mcasimir** [comment]
@fuzhentao there were some issues closed about that, so to answer your question: yes someone has used it. 

Probably better to ask such questions on http://mobileangularui.com/forum/ you will find more users there that will share their opinion with you.
