### ISSUE TITLE
ui Switch is throwing error during $destroy

### ISSUE THREAD

**Issue by sankp** [mcasimir/mobile-angular-ui#269]
Line number 3503 : var unbind = angular.noop();

It looks like instead of angular.noop it is declared as angular.noop()
Because of this while doing navigation switch control is throwing error on line 3534 : unbind();

Correcting line 3503 : var unbind = angular.noop; fixes the issuse.

**Comment by mcasimir** [comment]
@sankp thanks, fixed by #258
