### ISSUE TITLE
Can't open modal from directive

### ISSUE THREAD

**Issue by ImenAmmar** [mcasimir/mobile-angular-ui#271]
I'm using highcharts and I want to open a modal when I click in a point from the chart. I'm creating my chart and updating it from a directive (link : scope.$watch) so I used: "$rootScope.Ui.turnOn('modal1')"  but the modal isn't opening. Could you help me to make it work?

**Comment by mcasimir** [comment]
@ImenAmmar you can probably find much more help on http://mobileangularui.com/forum/ and stackoverflow.

Please use the issue tracker for issues related code only. About your current problem, new website will have better documentation and more interactive examples. Also a comment box under each doc sections. 

Thanks!
