### ISSUE TITLE
Change the title dynamically depending of current Page

### ISSUE THREAD

**Issue by estvmachine** [mcasimir/mobile-angular-ui#272]
This is from the template,  how can i make the 'title' show the name of the current Page or the $state of the view (i'm using ui.router instead of ngRoute). But the idea is show in the 'title' the name of the 'state'. How i can do that?. I have to pass that value from child to the parent i think.

```javascript
  <!-- Navbars -->
     <div class="navbar navbar-app navbar-absolute-top">
        <div class="navbar-brand navbar-brand-center" ui-yield-to="title">
            <span data-ng-bind="title"></span>
        </div>
     </div>

```

**Comment by estvmachine** [comment]
I saw in the demo, the views have something like this:

```html
<div ui-content-for="title">
  <span>Scroll</span>
</div>
```

And well the 'ui-yield-to="title"' show the span with 'Scroll', what directive do this?

**Comment by mcasimir** [comment]
@estvmachine `ui-content-for` and `ui-yield-to`
