### ISSUE TITLE
error installing yeoman generator

### ISSUE THREAD

**Issue by drkhannah** [mcasimir/mobile-angular-ui#274]
npm ERR! Darwin 14.3.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "-g" "generator-mobileangularui"
npm ERR! node v0.12.2
npm ERR! npm  v2.11.2
npm ERR! code ELIFECYCLE

npm ERR! unicode@0.6.1 postinstall: `node install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the unicode@0.6.1 postinstall script 'node install.js'.
npm ERR! This is most likely a problem with the unicode package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node install.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls unicode
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hannade/Developer/yoRDC/npm-debug.log

**Comment by mcasimir** [comment]
@drkhannah `yo mobileangularui` has been updated since that. But please post this kind of issues to the right repo: https://github.com/mcasimir/generator-mobileangularui
