### ISSUE TITLE
ui-content-for does not update when he is inside ui-if and view is changed (ui-router)

### ISSUE THREAD

**Issue by sam2x** [mcasimir/mobile-angular-ui#275]
Hey,

I have read a lot of tickets related to ui-content-for/ui-yield-to. Some of them are similar. So i followed the 'hack' where you emit a ng-router route change inside the ui-router run. Thus, it solved a problem, but i have still a weird behaviour with ui-content-for.

Here we go, i have : 

* v1 which is my home page
* v2 which is a page containing two tabs (let's call them v2tab1 v2tab2 )
* Also, there is a bottom navbar which is dynamically updated via a  ui-content-for tag inside div WHEN switching between v1 and v2 AND when switching between v2tab1, and v2tab2. The default v2 navbar-bottom content is the one from the tab1 (v2tab1). 

Now the weirdz bug. When i load my application http://app/v2_view everything is working fine. switching tabs will update navbar bottom. 
BUT then, i load http://app/v1_view (or i navigate directly inside the app), and when i load v2_view, i have the correct v2tab1 navbar-bottom, but if i switch to v2tab2, the navbar-bottom wont change, it stay the same. If i load directly the v2_view, it works, but when i switch view and come back to v2_view, clicking to tab2 wont load his ui-content-for :s...

So i was thinking the hack provided works only when we are switching view. Here when i go to v2tab2 the view isnt changed, should i trigger a specific events to fire the 'ui-content-for' contents? 

Thx, hope my explanation is clear!

**Comment by sam2x** [comment]
Okey i solved it... I had something like this : 

    <div class="btn-group justified" ui-yield-to="footer_nav" ui-view='footer'></div>

I used a specific view "footer" that allowed me flexibility inside my routing logi. So i could specify something like : 

            views: {
                "main": {
                    templateUrl: 'Bla.html',
                    controller: 'BlaController'
                },
                "footer":{
                   templateUrl:"bla_footer.html", 
                }
            },

I thought i could have the two. That was the wrong thing to do. It was conflicting with the ui-yield-to (didnt go deep in code source). I just removed it, and it worked : 

    <div class="btn-group justified" ui-yield-to="footer_nav"></div>

Hope it helps someone else.

**Comment by sam2x** [comment]
Another important thing i just noticed.
My ui-content-for seems to be triggered correctly only when it is inside a 'ui-if' block not before.

So in my project, something like that does **not** trigger the block correctly(*) : 

    <ui-state id='isPrinted' default='1'></ui-state>
	<div ui-content-for="footer_nav">
	    <div class="btn btn-navbar">
	        <a ui-set="{'isPrinted':1}">
	            <i class="fa fa-search">TAB1</i>
	        </a>
	    </div>
	    <div class="btn btn-navbar">
	        <a ui-set="{'isPrinted':2}">
	            <i class="fa fa-search">TAB2</i>
	        </a>
	    </div>
	</div>
    <div ui-if="isPrinted == 1" class="content section scrollable scrollable-content container-fluid">
          [code]
    </div>

And, something like that trigger the correctly(*) the block : 

    <ui-state id='isPrinted' default='1'></ui-state>
    <div ui-if="isPrinted == 1" class="content section scrollable scrollable-content container-fluid">
	  <div ui-content-for="footer_nav">
	    <div class="btn btn-navbar">
	        <a ui-set="{'isPrinted':1}">
	            <i class="fa fa-search">TAB1</i>
	        </a>
	    </div>
	    <div class="btn btn-navbar">
	        <a ui-set="{'isPrinted':2}">
	            <i class="fa fa-search">TAB2</i>
	        </a>
	    </div>
	  </div>
      [code]
    </div>

I don't know the reason of behaviour (i suspect the inside block code to be "binded" to an event which 'trigger' the ui-content-for, and this event doesnt find the ui-content-for when he is outside the block code). But well, it works now. Hope it helps someone else.

**Comment by Amerr** [comment]
hey @sam2x  does mobileangularui requires . UI router https://github.com/angular-ui/ui-router

**Comment by mcasimir** [comment]
@sam2x Great, looking if we can add some notice about this to docs. (there will be a dedicated section for integration with ui-router)

@Amerr no `mobileangularui` does not require `ui-router` at all.

**Comment by sarmadbokhari** [comment]
hey @mcasimir would you happen to know how I can get mobileangularui working with ui-router, I set everything up but the uiSidebarLeft won't open.
