### ISSUE TITLE
Reset ui-yield-to templates on routeChangeSuccess instead of routeChangeStart

### ISSUE THREAD

**Issue by atd** [mcasimir/mobile-angular-ui#282]
`ui-yield-to` templates are reset on `routeChangeStart`

https://github.com/mcasimir/mobile-angular-ui/blob/master/src/js/core/capture.js#L120

This makes impossible canceling the route change with `preventDefault`. Templates are always cleaned up.

Using `routeChangeSuccess` should be safe, as `ngView` has not instantiated the controller and rendered the new view yet

https://docs.angularjs.org/api/ngRoute/service/$route

**Comment by mcasimir** [comment]
Hi @adt, have to confirm but great catch. Going to schedule it for next release!

**Comment by atd** [comment]
Good @mcasimir ! Can you provide an approximate date? We might need using a fork in the meantime

**Comment by mcasimir** [comment]
Well if u have to fork just for this please submit a PR or just send me the change and i can merge and release a new tag tomorrow.

**Comment by mcasimir** [comment]
is it just

``` js
       $rootScope.$on('$routeChangeStart', function() {
```

to

``` js
       $rootScope.$on('$routeChangeSuccess', function() {
```

?

I can review this briefly, tests should catch any problems due to this change but in general I don't see big issues.

**Comment by atd** [comment]
Awesome! Yes, it is just that change

**Comment by atd** [comment]
@mcasimir could you please make a release? I am sorry for the hurries but we have a deadline and we need this fix

**Comment by mcasimir** [comment]
Tag `v1.2.0-rc.3` contains the fix. Thanks

**Comment by atd** [comment]
It works like a charm! Thank you Maurizio
