### ISSUE TITLE
Download link broken

### ISSUE THREAD

**Issue by cjlack** [mcasimir/mobile-angular-ui#295]
Download on http://mobileangularui.com/ points to https://github.com/mcasimir/mobile-angular-ui/archive/.zip which gives a 404.

**Comment by cjlack** [comment]
Still broken. I was wondering how well maintained Mobile AngularJS UI is. Perhaps I have my answer...

**Comment by alenb** [comment]
+1

**Comment by davidfasanisab** [comment]
+1

**Comment by bensontrent** [comment]
+1 Download link still broken at http://mobileangularui.com/ via the main download button on the home page.

404: https://github.com/mcasimir/mobile-angular-ui/archive/.zip

**Comment by sergiorb** [comment]
+1

**Comment by mcasimir** [comment]
solved
