### ISSUE TITLE
Updating Fastclick

### ISSUE THREAD

**Issue by am3000** [mcasimir/mobile-angular-ui#301]
Hi, I´m having this issue as described here: http://stackoverflow.com/questions/32034503/links-and-clicks-fail-to-open-with-cordova-on-ios-8-4-1

A suggested solution seems to be updating Fastclick.
How can I update it to the latest version in maui?

**Comment by lylepratt** [comment]
@mcasimir This is REALLY important. Mobile Angular UI is basically broken on the latest version of iOS. How can we update the version of fastclick used with Mobile Angular UI?

**Comment by n9986** [comment]
I concur. This has rendered an app completely useless on iOS.

**Comment by am3000** [comment]
In my case it could be fixed with css, but I guess that´s not the best way to do it ...

    a, button { opacity:1 !important; }

Strange but worked:

**Comment by lylepratt** [comment]
That MAY fix it for `a` and `button` elements, but any other element with ng-click behavior would still be broken.

**Comment by am3000** [comment]
Sure, just wanted to share it as it´s a lifesafer when your app is going to go live tomorrow.

**Comment by hobe** [comment]
i also need a fixed version of MobileAngularUI very quick! our app is currently useless...

**Comment by lylepratt** [comment]
For now, I installed the latest version of Fastclick via bower ON TOP of maui, and it solved my problem.

**Comment by hobe** [comment]
so is it enough to change the bower.json to 
 "fastclick": "1.0.6"

and rebuild the current sources?

**Comment by CyborgMaster** [comment]
I have been having the same problem and I installed FastClick on top of MAUI.  I would love to see MAUI's dependencies (font-awesome, bootstrap, fastclick, and overthrow), included as runtime dependencies instead of compile time ones.  This would give me a lot more customizability for dealing with issues like this on my own.

**Comment by raywu** [comment]
Any update on this issue. @lylepratt can you share how you configure FastClick with MAUI? Which version of MAUI?

**Comment by lylepratt** [comment]
I just overrode the MAUI included with my own bundled version and made sure it loaded AFTER MAUI.

**Comment by raywu** [comment]
I found that removing ['mobile-angular-ui.plugins.ui-router'](https://github.com/angular-ui/ui-router/issues/1140) on bower and updating to MAUI 1.2.0 works. But the view is screwed up (need to reskin). I don't fully understand [why we need this module or how to get around it](https://github.com/angular-ui/ui-router/issues/1140)

**Comment by CyborgMaster** [comment]
Any update on this?  I would love to remove extra version of fastclick from our project.
