### ISSUE TITLE
iOS 9 clicks

### ISSUE THREAD

**Issue by Batska** [mcasimir/mobile-angular-ui#303]
Sidebar links don't open, whether accessed by href directly, ng-click, or ng-href. It works fine in iOS 9 Safari, but does not work in PhoneGap. Part of links works fine, except sidebar links.
I've tried:
- FastClick 1.0.6 (replace a part of mobile-angular-ui.js)
- .btn:active, a:active { opacity: 1 !important }
- Function $rootScope.go instead of href
- .btn { z-index: 999999 }
- PhoneGap 5.1.1
- PhoneGap 3.7

Due this error, Apple second time rejects my .ipa

**Comment by dribehance** [comment]
i run into the same problem

**Comment by Batska** [comment]
Solution:
Step 1. Write function $rootScope.go(url) and use it instead of href:
```javascript
  $rootScope.go = function(path){
    $location.path(path);
  };
```
Step 2. Create ngMobileClick directive to use touchstart event:
```javascript
app.directive('ngMobileClick', function( $parse ) {
   return {
       restrict: 'A',
       link: function (scope, elem, attrs) {
        elem.bind("touchstart click", function (e) {
            e.preventDefault();
            e.stopPropagation();
            scope.$apply(attrs["ngMobileClick"]);
        });
      }
    }
});
```
Step 3. Use ng-mobile-click="go('/url')" instead of href="#/url" in sidebar.html:
```javascript
<a class="list-group-item" ng-mobile-click="go('/candidates')"><i class="fa fa-users"></i> Кандидаты <i class="fa fa-chevron-right pull-right"></i></a>
```

**Comment by xjmalm** [comment]
Thanks Batska for the solution.
But it seems the current menu in sidebar is no longer marked as selected.

**Comment by dribehance** [comment]
thanks Batska ,by the time i comment i hava use step 1 to resolve,but dont know why
