### ISSUE TITLE
Download link on web doesn't work

### ISSUE THREAD

**Issue by mikaere** [mcasimir/mobile-angular-ui#304]
Hi,

Download button goes to https://github.com/mcasimir/mobile-angular-ui/archive/.zip which give 404

 Maybe https://github.com/mcasimir/mobile-angular-ui/archive/master.zip or 1.0 release...?

Regards,
Mike

**Comment by zhang-z** [comment]
Hi, issue #295 is saying the same issue. Maybe you want to close this one
