### ISSUE TITLE
:hover not working

### ISSUE THREAD

**Issue by abhijitghogre** [mcasimir/mobile-angular-ui#310]
How to get CSS :hover to work in mobile-angular-ui on desktop devices?

**Comment by mcasimir** [comment]
Hi, `:hover` is intentionally excluded from mobile css, you should include desktop css too to make it work.

**Comment by Jason7Le** [comment]
http://stackoverflow.com/questions/905033/how-to-use-hover-in-css

**Comment by abhijitghogre** [comment]
I tried including ```mobile-angular-ui-desktop.less``` and ```mobile-angular-ui-hover.css```.
Still no luck.
