### ISSUE TITLE
Broken download link on http://mobileangularui.com

### ISSUE THREAD

**Issue by alvarod-infocorp** [mcasimir/mobile-angular-ui#323]
The download link is broken - [here] (http://mobileangularui.com/)

**Comment by bsiete2000** [comment]
it is! please fix it

**Comment by ciromattia** [comment]
In the meantime @mcasimir gets this up&running again, you can download from Releases tab (https://github.com/mcasimir/mobile-angular-ui/archive/v1.2.0-rc.3.zip) or install via bower.

**Comment by mcasimir** [comment]
Thanks, it seemed a quick fix but It involves a bigger issue, i'll apply a
temporary patch in case it would drag too long.

Il giorno gio 12 nov 2015, 09:45 Ciro Mattia Gonano <
notifications@github.com> ha scritto:

**Comment by alvarod-infocorp** [comment]
many thanks! regards

**Comment by mcasimir** [comment]
Fixed
