### ISSUE TITLE
Is it possible to disable swipe right, in order to DON'T open the sidebar menu?

### ISSUE THREAD

**Issue by NunoBento** [mcasimir/mobile-angular-ui#326]
My application needs to **open the sidebar right in a few pages**, but in other pages it shouldn't open.

For example, if i'm using google maps and i swipe right, i don't need the sidebar menu to open because i'm just scrolling. 

How can i prevent the sidebarmenu from opening?

**Comment by ErickXavier** [comment]
My case is close to this: I would like to disable the swipe right in certain case only, I'm using an outside plugin for Carousels, and when we slide right, the sidebar opens. I don't want it.

**Comment by ErickXavier** [comment]
Hi, answering myself: there's swipe demo that does exactly what I want.
It's here: http://mobileangularui.com/demo/#/swipe

Just need to use the directives ui-swipe-left ui-swipe-right to the element that we want to swipe by itself without dragging the menu with it. Those directives accepts functions too.

;)

**Comment by NunoBento** [comment]
That just solved it, it was exacly what i was looking for! 
thanks ErickXavier :)

**Comment by andrea-86** [comment]
I have the same problem, and i know this solution but is not workingfor me.
Like in demo i have an index page, and then add content in view otherwhise in <ng-view> tag
here's some code.
In the controller of the content section i write:

```
"content": {
						templateUrl: 'views/page1.html',
						controller: function($scope) {
							$scope.$watch('ready', function() {
								$('.app').addClass('transparent');
								$('body').addClass('transparent');
								$scope.swiped = function(direction) {
									alert('Swiped ' + direction);
								};
								engine.camera.initialize();
							});
							$scope.on("$destroy", function(){
								alert("destroy");
								$('.app').removeClass('transparent');
								$('body').removeClass('transparent');
							})
							
						}
					}
```
and then in page1.htlm: 

```
<div id="guidelines-mask"
	ui-swipe-left='swiped("LEFT")'
   ui-swipe-right='swiped("RIGHT")'></div>
```

that's a div with position absolute tha cover all the screen.

How can i do

**Comment by NunoBento** [comment]
i've got to say, i'm not a pro in this affair, i'm gonna tell how i solved it.

but what i did was: in the div i didn't want to open the menu, i used ui-swipe-right=''
here is the demo html page:
view-source:http://mobileangularui.com/demo/swipe.html
click ctrl+u to see the source

instead of a div absolute position, try this:
```
<div class="scrollable">
   <div class="scrollable-content section" 
      ui-swipe-left=''
      ui-swipe-right=''>
```
tell me if it worked :p

**Comment by andrea-86** [comment]
i've just tried this solutoin and dosn't worked....this is very strange behavior
