### ISSUE TITLE
Missing dist/js/mobile-angular-ui.components.min.js

### ISSUE THREAD

**Issue by karneaud** [mcasimir/mobile-angular-ui#328]
Your documentation mentions a file *dist/js/mobile-angular-ui.components.min.js* But in the **yo** generated project I don't seem to see it

There is however a 

*./bower_components/mobile-angular-ui/src/js/mobile-angular-ui.components.js* so I assume this is what I'm looking for

However when trying load certain components with the configuration

```
vendor: {
    js: [
      './bower_components/angular/angular.js',
      './bower_components/angular-route/angular-route.js',
      './bower_components/mobile-angular-ui/dist/js/mobile-angular-ui.core.min.js',
      './bower_components/mobile-angular-ui/dist/js/mobile-angular-ui.gestures.min.js',
      './bower_components/mobile-angular-ui/dist/js/mobile-angular-ui.migrate.min.js',
      './bower_components/mobile-angular-ui/src/js/mobile-angular-ui.components.js',
      './bower_components/mobile-angular-ui/src/js/migrate/overlay.js',
      './bower_components/mobile-angular-ui/src/js/migrate/forms.js',
      './bower_components/mobile-angular-ui/src/js/migrate/switch.js',
      './bower_components/mobile-angular-ui/src/js/components/modals.js'
    ],
```

I get the error

https://docs.angularjs.org/error/$injector/nomod?p0=mobile-angular-ui.components.modals

> Error: $injector:nomod
   Module Unavailable
   Module 'mobile-angular-ui.components.modals' is not available! You either misspelled the module name or forgot to load it. If registering a module ensure that you specify the dependencies as the second argument.

Did I stumble upon a bug?

**Comment by sam2x** [comment]
Your missing module is referenced in the src repo : 

https://github.com/mcasimir/mobile-angular-ui/blob/ab20a91e700dcb14fc859699b1a75aca549e2c3f/src/js/components/modals.js

You installed the last version ?

**Comment by cyberkatze** [comment]
@karneaud solved ?

**Comment by karneaud** [comment]
I ditched yo and went with my own custom stuff. Thanks
