### ISSUE TITLE
Images not displaying

### ISSUE THREAD

**Issue by HarryWiseman** [mcasimir/mobile-angular-ui#339]
Hi,

When I debug the app in browser (acting like an iPad) everything is fine, however when I run the app either through the emulator or by using the PhoneGap Developer app on iPad none of the images that are in the HTML load.

On initial load the image on the home page is shown but when you navigate away and come back to the home page it no longer shows.

I am using Angular routing to display different templates based on the route and referencing the images by images/... or /images/... and neither work.

If you could help shed some light on this it would be amazing.

Thanks

Harry

**Comment by mcasimir** [comment]
Hi Harry, your issue does not seem strictly related to mobile-angular-ui, maybe you can report this on forum. 

Feel free to reopen if you find the cause to be mobile-angular-ui
