### ISSUE TITLE
CAN'T DOWNLOAD... 

### ISSUE THREAD

**Issue by sipi41** [mcasimir/mobile-angular-ui#340]
I think the link is broken... on the main page where says download take you to a NOT FOUND page... something wrong?

**Comment by DavidCaswell** [comment]
Link is still broken...

**Comment by sheetaldshivdas** [comment]
Page not found error...please fix asap...

**Comment by sureshpathi10** [comment]
Not fixed yet. Still the link is down.

**Comment by mcasimir** [comment]
Fixed
