### ISSUE TITLE
Explicitly define FastClick?

### ISSUE THREAD

**Issue by krilina** [mcasimir/mobile-angular-ui#353]
Hi, I am loading the lib with requirejs and I get the following error:

> Error: Mismatched anonymous define() module: 
> function () {
> 		"use strict";
> 		return FastClick;
> }
> http://requirejs.org/docs/errors.html#mismatch

Which relates to a resolved issue in fastclick lib  #https://github.com/ftlabs/fastclick/issues/281.

Would it be possible to update the lib and get the fix?

Thank you!

**Comment by mcasimir** [comment]
@krilina updated fastclick version is present in `pipeline-refactor` branch and will be merged soon!

Thanks for reporting!
