### ISSUE TITLE
Errors in downloaded library code

### ISSUE THREAD

**Issue by sahilbabbar** [mcasimir/mobile-angular-ui#356]
Hi,

Recently, downloaded this library and opened ```demo/index.html``` but it rendered like following:
![screen shot 2016-04-17 at 9 59 50 pm](https://cloud.githubusercontent.com/assets/6317330/14588463/fb359074-04e7-11e6-8676-0e25f7cdd9eb.png)
Due to following errors:
![screen shot 2016-04-17 at 9 59 41 pm](https://cloud.githubusercontent.com/assets/6317330/14588466/0030217a-04e8-11e6-9d92-70c8e08731ed.png)

**Comment by sahilbabbar** [comment]
@mcasimir any idea?

**Comment by cyberkatze** [comment]
@sahilbabbar stupid simple.... just copy DIST folder into your demo folder and then you can start web-server with nodeJS [http-server](https://www.npmjs.com/package/http-server)!

**Comment by sahilbabbar** [comment]
@cyberkatze stupid thanks!

**Comment by yueming-Chen** [comment]
@cyberkatze hello,I did the same step copy dist to demo floder and start web-server,but it didn't work.
it's display the same wrong console.
![image](https://cloud.githubusercontent.com/assets/13268649/17687640/5be6f0dc-63a9-11e6-8470-60ce4b2b47ec.png)
any idea?
