### ISSUE TITLE
Namespace clashing with ui-router (Could not resolve 'undefined' from state 'foo')

### ISSUE THREAD

**Issue by ryanannatuvasquez** [mcasimir/mobile-angular-ui#361]
Hi I'm using overlay modal but everytime I click anywhere in modal I always got this error
```
angular.js:13550 Error: Could not resolve 'undefined' from state 'foo'
```

FYI, im using `ui.router`.
here is my modal

```html
<div class="modal modal-overlay" ui-if='someModel' ui-state='someModel'>
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button class="close"
                ui-turn-off="someModel">&times;</button>
                <h4 class="modal-title">Signature</h4>
            </div>
            <div class="modal-body">
                <!-- code here -->
            </div>
            <div class="modal-footer">
                <button ui-turn-off="someModel" class="btn btn-default">Close</button>
                <button ui-turn-off="someModel" class="btn btn-primary">Save changes</button>
            </div>
        </div>
    </div>
</div>

```

**Comment by vkarampinis** [comment]
I have the same problem!

**Comment by ryanannatuvasquez** [comment]
I solved my problem by manually initiating the `sharedState` in controller and not using the `ui-state` directive in the modal.
```js
SharedState.initialize($scope, 'someModel', false);
```
but still hoping for better fix `ui-router` has richer APIs.

**Comment by mcasimir** [comment]
I'll consider renaming the prefix, although it would fit for a major release i can think about distributing some sort of `no-conflict` version.

Going to accept and schedule it somehow. Thanks for reporting it.

**Comment by mcasimir** [comment]
@ryanannatuvasquez Would it be a reasonable fix to alias `ui-state` to something else (`ui-shared-state`) and deprecate `ui-state`?

**Comment by mcasimir** [comment]
https://github.com/mcasimir/mobile-angular-ui/pull/374

**Comment by ryanannatuvasquez** [comment]
@mcasimir `ui-shared-state` is a nice fix to avoid conflict 👍 💯
Closing this issue now since it has now been resolved.
Thank you for this fix!
