### ISSUE TITLE
Scroll bar color

### ISSUE THREAD

**Issue by chanmyaesoe** [mcasimir/mobile-angular-ui#366]
Hi..
I would like to say thank you first.
May I know something about scroll bar color.
Can I change scroll bar color in Mozilla?. If can , please let me know.

**Comment by mcasimir** [comment]
Although it simulate scrolling on old devices mobile angular ui does not affect scroll bar style. I know about some css for webkit but i think you'll find better answers about this topic on stackoverflow or some other specific forum.
