### ISSUE TITLE
SharedState events

### ISSUE THREAD

**Issue by napcat** [mcasimir/mobile-angular-ui#368]
Hello guys,

I need to know every time the side menu is open.

Is there any event in to listen to "uiSidebarLeft" change?

**Comment by napcat** [comment]
I already found the solution:

> $rootScope.$on('mobile-angular-ui.state.changed.uiSidebarLeft', function (e, newVal, oldVal)
> {
>     ...
> })

**Comment by mcasimir** [comment]
Closing as solved
