### ISSUE TITLE
scrollTo element incorrect when you have a scrollable-header

### ISSUE THREAD

**Issue by byronigoe** [mcasimir/mobile-angular-ui#369]
1. Create a scrollable with a scrollable-header & scrollable-content.
2. Add an input element in the scrollable-content.
3. On a mobile device, click in the input element to bring up the virtual keyboard.
4. The directive tries to ensure the input is visible, but the calculation is off by the height of the scrollable-header.

The offending code is in scrollable at 129. It needs to consider the scrollable's top padding. Instead of:
`scrollableContent.scrollTop = target.offsetTop - marginTop;`
I think it should be:
`scrollableContent.scrollTop = target.offsetTop - marginTop - (target.offsetParent && target.offsetParent.style.paddingTop ? parseInt(target.offsetParent.style.paddingTop.substring(0, target.offsetParent.style.paddingTop.length - 2)) : 0);`

This works, but it's ugly. Is there a cleaner way of getting the size of the scrollable-header?

**Comment by daniel-prinsloo** [comment]
Hi byronigoe

I found the same issue you raised a few months ago and forked a repo with a fix that I am quite sure is battle tested on iOS and Android.

When you raised this issue I created a pull request for the master branch: 
**#370 Soft-Keyboard and scrollTo compensation with regard to scrollableHeader.**

 You can go look at the forked repo to see that I did find this months ago at:
https://github.com/daniel-prinsloo/mobile-angular-ui/tree/master-scrollable-content-fix

Although I think the code that is part of the pull request is the cleanest way of achieving this fix.

The "**scrollable.scrollableContent.parentElement.querySelector(".scrollable-header")**" method of obtaining a scrollable header if present is the fastest according to my reseach as it only searches for the first element found and it starts it search with .scrollable and will find it immediately.

**Comment by mcasimir** [comment]
Closing in favor of #370

**Comment by daniel-prinsloo** [comment]
New updated pull request #371 

Fixed my forked repo and updated the pull request from master to master with the pipeline-refactor already pulled in. 

Please see my extra comments on the pull request.

**Comment by mcasimir** [comment]
@daniel-prinsloo, @byronigoe  the mr is merged.

I don't think is easily feasible to add a test for the original use case, the one where the keyboard is triggered (please tell me if i'm wrong).

I'll try to do something about the scroll to feature in general.

I believe we are fine, it takes care both of the situation with and without the header. Anyway before to spend time on that I'd like to hear some thoughts from you guys about this specific solution, especially about what @byronigoe was saying here: https://github.com/mcasimir/mobile-angular-ui/pull/371#issuecomment-238948892

I didn't really got the concern... sorry. It would be great if you can clarify it. Thanks!
