### ISSUE TITLE
Safari not displaying the Demo

### ISSUE THREAD

**Issue by jayze** [mcasimir/mobile-angular-ui#380]
Hi,

When using Safari and opening the DEMO page, I get a cricle that it's loading. On Chrome / FF it's working great. No plugins are installed on Safari. Anyone an idea why this isn't working on Safari (OSX)

Thanks.

**Comment by mcasimir** [comment]
Hi jayze, thanks for reporting this, it is a problem with the demo itself. I've fixed it, i'm gonna redeploy the website in a few hours along with the a new release.
