### ISSUE TITLE
Swipe unbind?

### ISSUE THREAD

**Issue by sudheerDev** [mcasimir/mobile-angular-ui#393]
I have a page setup where ui-swipe-x is part of nested state. This directive gets destroyed while transitioning to few routes.

Should the ui/ ng swipe directive unbind `$swipe` service when destroyed?

```
  angular.forEach(['ui', 'ng'], function(prefix) {
    angular.forEach(['Left', 'Right'], function(direction) {
      var directiveName = prefix + 'Swipe' + direction;
      module.directive(directiveName, ['$swipe', '$parse', function($swipe, $parse) {
        return {
          link: function(scope, elem, attrs) {
            var onSwipe = $parse(attrs[directiveName]);
            $swipe.bind(elem, {
              end: function(swipe, event) {
                if (swipe.direction === direction.toUpperCase()) {
                  if (!event.__UiSwipeHandled__) {
                    event.__UiSwipeHandled__ = true;
                    scope.$apply(function() {
                      onSwipe(scope, {$touch: swipe});
                    });
                  }
                }
              }
            });
          }
        };
      }]);
    });
  });
```

**Comment by nijk** [comment]
A bit late for the original poster but here's an answer for others:

The documentation for the $swipe service shows that the [bind method](http://mobileangularui.com/docs/module:mobile-angular-ui/module:gestures/module:swipe#bind) returns a function that will unbind the event listeners when called. Therefore I believe it is the responsibility of the implementing developer to provide a listener for the $destroy event that unbinds the $swipe listener(s). 

Example:
```
var unbind = $swipe.bind(elem, {
  end: function(touch) {
    console.log('Swiped:', touch.direction);
  }
});

scope.$on('$destroy', function() {
  unbind();
});
```

The correct scope will depend on where you are calling this code from, the example above is from a custom directive. If the implementation were in a Controller then I believe `$scope` would normally be correct.
