### ISSUE TITLE
yieldTo and contentFor should work even if yieldTo is added after contentFor

### ISSUE THREAD

**Issue by ejensler** [mcasimir/mobile-angular-ui#88]
I would like to request easier on/off toggling of the navbar in a future release. I don't think my particular use-case is that uncommon.  I have authentication handled by angular, and thus I want the navbar hidden for the login screen, registration screens, etc. that are "outside" the main portion of the app. In my app, I am using an `ng-hide` directive to toggle the top navbar div on and off using a $rootscope variable (`navbarOff`) that I change depending on the route, which works fine. The problem is that this means that the `.has-navbar-top` is applied to the `<div class="app">`, so padding is applied to the view even though the navbar is not visible. On scrollable views, this means the content is awkwardly cut off 50px from the top of the screen when scrolled. If I use an `ng-if` rather than an `ng-hide` on the navbar, then the `content-for` and `yield-to` directives don't work properly.

My solution was to comment out the `navbarAbsoluteTop` directive that adds the `.has-navbar-top` class, and then add `ng-class="{'has-navbar-top': !navbarOff}` to the `<div class="app">` tag. This is of course slightly breaking the framework.

**Comment by am3000** [comment]
Seems this does not work any more? See your Plunker
